### ISSUE TITLE
Support for ENV variables

### ISSUE THREAD

**Issue by 0xdevalias** [coppit/docker-duckdns#2]
It would be really cool if you could add support for passing in the domain, token and interval as environment variables (falling back to the config file if they're missing)

That way we could easily update through the unraid GUI.

**Comment by coppit** [comment]
Aren't you mapping the config dir to a dir on the host, so that the settings are persistent? If you do that, updating the container is a snap.

Or are you wanting to update the config values more easily through the unraid GUI? Seems like a low priority, since (1) these values hardly ever need to change, and (2) this would be a benefit mainly to users of this container who use it though unraid.

**Comment by 0xdevalias** [comment]
More the 2nd (unraid) option. It's minimal now that it's setup, but would have made it easier to get going in the first place.

**Comment by kolleroot** [comment]
I had the same problem and I found, that you can leave the duck.conf empty and set the ENV var like `docker run -e "DOMAINS=<yourdomain>" -e "TOKEN=<token>" -e "INTERVAL=5m" -v <somedir>:/config --rm coppit/duckdns`. You have to create an empty file named `duck.conf` in <somedir> so the script doesn't create a new one and the ENV vars won't be overwritten.

**Comment by coppit** [comment]
Cool! I added this to the README:

> If you prefer to set environment variables for your docker container instead of using the configuration file, simply comment out the vars in the duck.conf. Note that the file needs to exist, or the container will recreate it.

Closing this, since that workaround is kinda the right solution. alias1, please reopen if it doesn't work for you.
